import type { Metadata } from "next";
import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";
import Footer from "./components/atoms/Footer/Footer";
import Header from "./components/atoms/header/Header";

const notoSansGeorgian = Noto_Sans_Georgian({
  weight: ['400', '500', '600', '700'],
  subsets: ['georgian'],
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSansGeorgian.className}`}>
      <body className="antialiased">
        <div className="container flex flex-col justify-center px-4 mx-auto h-full overflow-hidden">
          <Header/>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
